name: Lint and Test
run-name: Lint and Test
on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Install Dependecies and Run Tests
        uses: ./.github/actions/setup

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm run test:ci
